### ISSUE TITLE
List to Object Map.

### ISSUE THREAD

**Issue by Manikgoyal** [erchu/bean-cp#15]
How to map the following case. I am getting Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0.

Code : 

               Person person = new Person();
		person.setName("Manik");
		Address address = new Address();
		address.setState("CHD");
		person.getAddresses().add(address);
		Employee employee = new Employee();
		Mapper mapper 
		= new MapperBuilder()
			.addMap(Person.class, 
					Employee.class,  
					(conf, source, destination) -> conf
					.bind(source::getName, destination :: setName)
					.bind(source.getAddresses().get(0) :: getState, destination ::setState)
					)
			.buildMapper();
		
		Employee emp=mapper.map(person, employee.getClass());

I am getting error due to this line
.bind(source.getAddresses().get(0) :: getState, destination ::setState)

How to resolve this issue.

Manik

**Comment by erchu** [comment]
Your map configuration is invalid for empty collection. Even your person instance has non empty collection of addresses, still map configuration should be able to handle empty collections. To sum up, here is correct version:

```
new MapperBuilder()
.addMap(Person.class,
		Employee.class,
		(conf, source, destination) -> conf
		.bind(source::getName, destination::setName)
		.bind(
				() -> (source.getAddresses().size() > 0 ? source.getAddresses().get(0).getState() : null),
				destination::setState))
.buildMapper();
```
